public class Main {

    public static void main(String[] args) {
        Employee ivanov = new Employee("Ivanov", "Ivan", "Ivanovich");
//        System.out.println(ivanov.getId());
        ivanov.setSalary(50_000);
        ivanov.setDepartmentNumber(1);
        Employee petrov = new Employee("Petrov", "Petr", "Petrovich");
//        System.out.println(petrov.getId());
        petrov.setSalary(100_000);
        petrov.setDepartmentNumber(1);
        Employee sidorov = new Employee("Sidorov", "Alexander", "Nikolaevich");
        sidorov.setSalary(45_000);
        sidorov.setDepartmentNumber(2);
        Employee nikolaev = new Employee("Nikolaev", "Nikolay", "Nikolaevich");
        nikolaev.setSalary(39_000);
        nikolaev.setDepartmentNumber(2);
        Employee alexandrov = new Employee("Alexandrov", "Alexander", "Alexandrovich");
        alexandrov.setSalary(70_000);
        alexandrov.setDepartmentNumber(3);
        Employee alexeev = new Employee("Alexeev", "Alexey", "Alexeevich");
        alexeev.setSalary(60_000);
        alexeev.setDepartmentNumber(3);
        Employee sergeev = new Employee("Sergeev", "Seregey", "Sergeevich");
        sergeev.setSalary(55_000);
        sergeev.setDepartmentNumber(4);
        Employee vasilyev = new Employee("Vasilyev", "Vasiliy", "Vasilievich");
        vasilyev.setSalary(67_000);
        vasilyev.setDepartmentNumber(4);
        Employee olgina = new Employee("Olgina", "Olga", "Olegovna");
        olgina.setDepartmentNumber(5);
        olgina.setSalary(150_000);
        Employee xeneva = new Employee("Xeneva", "Xenia", "Konstantinovna");
        xeneva.setSalary(200_000);
        xeneva.setDepartmentNumber(5);
//        System.out.println(vasilyev.getId());
        EmployeeBook employees = new EmployeeBook(new Employee[10]);
        employees.putEmployee(ivanov);
        employees.putEmployee(petrov);
        employees.putEmployee(sidorov);
        employees.putEmployee(nikolaev);
        employees.putEmployee(alexandrov);
        employees.putEmployee(alexeev);
        employees.putEmployee(sergeev);
        employees.putEmployee(vasilyev);
        employees.putEmployee(olgina);
        employees.putEmployee(xeneva);
        employees.printEmployeeList();
        System.out.println("Total expenses for salaries: " + employees.getExpensesTotal());
        employees.findMinSalary();
        employees.findMaxSalary();
        System.out.println("Medium salary: " + employees.getMediumSalary());
        employees.getAllNames();
        employees.indexAllSalaries(10);
        employees.printEmployeeList();
        employees.findMinSalaryDepartment(1);
        employees.findMaxSalaryDepartment(2);
        System.out.println("Total expenses in department 4: " + employees.getTotalSalaryDepartment(4));
        System.out.println("Medium expenses in department 3: " + employees.getMediumSalaryDepartment(3));
        employees.indexSalariesInDepartment(4, 10);
        employees.printDepartment(4);
        employees.findSalaryHigherThan(300000);
        employees.findSalaryLowerThan(10000);
        employees.deleteEmployeeByID(6);
        employees.createEmployee("Cardholder", "Name", "Sberbankovich", 42000, 1);
        employees.printDepartment(1);
        employees.printEmployeeNamesByDepartments();
    }
}